spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        Type: TRACE
      springframework:
        web.servlet.mvc: DEBUG
