ALTER TABLE requests
    ADD COLUMN affected_entity_id BIGINT DEFAULT NULL,
    ADD COLUMN locked_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    ADD COLUMN performed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
;
