app:
  vault:
    keyName: payments-platform-tk
    transitPath: payments-platform-transit
    enabled: false
  billing:
    url: "https://apidev-internal.ondemandenv.dev:8443/v1/billing/payments/event"
    apiKey: "1eAyUl1RkFVuGZMNTGnGy8703amikWBy"
  retry-backoff:
      initialInterval: 2000
      multiplier: 2.0
      maxInterval: 300000
  publish-events-scheduled: 1000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_platform
    username: payments_platform
    password: payments_platform
  jpa:
    properties:
      hibernate:
        # This must match the spring.flyway.schemas config
        # in db-migration's application.yaml
        default_schema: payments_platform
        types:
          print:
            banner: "false"
